### ISSUE TITLE
Add a LICENSE file, please

### ISSUE THREAD

**Issue by ninedraft** [frantchessico/zogo#2]
Hello!

I wanted to express my appreciation for your library; it's undoubtedly an impressive piece of work. However, there's a single issue that is preventing me from integrating it into my project – the absence of a LICENSE file.

I cannot stress enough the significance of a proper software license. It serves as a protective measure for both you, as the developer, and the users of your clients. By having a clear and well-defined license in place, you can mitigate potential legal complications down the line and establish a transparent framework for the usage and distribution of your software.

Incorporating a LICENSE file is a standard practice in the open-source community, and it provides users with the information they need to understand their rights and responsibilities when utilizing your library. Furthermore, it enables others to contribute to your project while adhering to the terms you set forth.

I kindly urge you to consider adding a LICENSE file to your repository. This action not only safeguards your work but also encourages wider adoption and collaboration. There are several widely-used open-source licenses available, such as the MIT License, Apache License, and GNU General Public License, each with its own set of conditions. Selecting an appropriate license for your project is an essential step towards fostering a vibrant and engaged user community.

Personally, I recommend MIT license, but you are free to choose https://choosealicense.com/ 

Thank you once again for your remarkable library. I genuinely believe that addressing this licensing matter will enhance its appeal and utility for potential users like me.

**Comment by frantchessico** [comment]
Hello, I hope you are well.
I would like to say that I am very grateful for the point of view. I apologize for the delayed response. But, I already added the LICENSE as you recommended.
Thank you one more time.
